// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

namespace GeoNRage.Server.Migrations
{
    public partial class UpdateGameTableRedoModel : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "Rows",
                table: "Games");

            migrationBuilder.RenameColumn(
                name: "Columns",
                table: "Games",
                newName: "Players");

            migrationBuilder.AddColumn<int>(
                name: "Rounds",
                table: "Games",
                type: "int",
                nullable: false,
                defaultValue: 5);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "Rounds",
                table: "Games");

            migrationBuilder.RenameColumn(
                name: "Players",
                table: "Games",
                newName: "Columns");

            migrationBuilder.AddColumn<string>(
                name: "Rows",
                table: "Games",
                type: "longtext CHARACTER SET utf8mb4",
                nullable: false,
                defaultValue: "Round 1_Round 2_Round 3_Round 4_Round 5");
        }
    }
}
