// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

namespace GeoNRage.Server.Migrations
{
    public partial class UpdatePlayerGuess : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<double>(
                name: "Distance",
                table: "PlayerGuesses",
                type: "double",
                nullable: true);

            migrationBuilder.AddColumn<int>(
                name: "Time",
                table: "PlayerGuesses",
                type: "int",
                nullable: true);

            migrationBuilder.AddColumn<bool>(
                name: "TimedOut",
                table: "PlayerGuesses",
                type: "tinyint(1)",
                nullable: false,
                defaultValue: false);

            migrationBuilder.AddColumn<bool>(
                name: "TimedOutWithGuess",
                table: "PlayerGuesses",
                type: "tinyint(1)",
                nullable: false,
                defaultValue: false);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "Distance",
                table: "PlayerGuesses");

            migrationBuilder.DropColumn(
                name: "Time",
                table: "PlayerGuesses");

            migrationBuilder.DropColumn(
                name: "TimedOut",
                table: "PlayerGuesses");

            migrationBuilder.DropColumn(
                name: "TimedOutWithGuess",
                table: "PlayerGuesses");
        }
    }
}
