// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

namespace GeoNRage.Server.Migrations
{
    public partial class UpdateGameMapTable : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_GameMap_Games_GameId",
                table: "GameMap");

            migrationBuilder.DropForeignKey(
                name: "FK_GameMap_Maps_MapId",
                table: "GameMap");

            migrationBuilder.DropPrimaryKey(
                name: "PK_GameMap",
                table: "GameMap");

            migrationBuilder.RenameTable(
                name: "GameMap",
                newName: "GameMaps");

            migrationBuilder.RenameIndex(
                name: "IX_GameMap_MapId",
                table: "GameMaps",
                newName: "IX_GameMaps_MapId");

            migrationBuilder.AddPrimaryKey(
                name: "PK_GameMaps",
                table: "GameMaps",
                columns: new[] { "GameId", "MapId", "Name" });

            migrationBuilder.AddForeignKey(
                name: "FK_GameMaps_Games_GameId",
                table: "GameMaps",
                column: "GameId",
                principalTable: "Games",
                principalColumn: "Id",
                onDelete: ReferentialAction.Cascade);

            migrationBuilder.AddForeignKey(
                name: "FK_GameMaps_Maps_MapId",
                table: "GameMaps",
                column: "MapId",
                principalTable: "Maps",
                principalColumn: "Id",
                onDelete: ReferentialAction.Cascade);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_GameMaps_Games_GameId",
                table: "GameMaps");

            migrationBuilder.DropForeignKey(
                name: "FK_GameMaps_Maps_MapId",
                table: "GameMaps");

            migrationBuilder.DropPrimaryKey(
                name: "PK_GameMaps",
                table: "GameMaps");

            migrationBuilder.RenameTable(
                name: "GameMaps",
                newName: "GameMap");

            migrationBuilder.RenameIndex(
                name: "IX_GameMaps_MapId",
                table: "GameMap",
                newName: "IX_GameMap_MapId");

            migrationBuilder.AddPrimaryKey(
                name: "PK_GameMap",
                table: "GameMap",
                columns: new[] { "GameId", "MapId", "Name" });

            migrationBuilder.AddForeignKey(
                name: "FK_GameMap_Games_GameId",
                table: "GameMap",
                column: "GameId",
                principalTable: "Games",
                principalColumn: "Id",
                onDelete: ReferentialAction.Cascade);

            migrationBuilder.AddForeignKey(
                name: "FK_GameMap_Maps_MapId",
                table: "GameMap",
                column: "MapId",
                principalTable: "Maps",
                principalColumn: "Id",
                onDelete: ReferentialAction.Cascade);
        }
    }
}
