// <auto-generated />
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;

namespace GeoNRage.Server.Migrations
{
    public partial class UpdateIds : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropPrimaryKey(
                name: "PK_PlayerGuesses",
                table: "PlayerGuesses");

            migrationBuilder.DropUniqueConstraint(
                name: "IX_PlayerGuesses_ChallengeId_PlayerId_Order",
                table: "PlayerGuesses",
                recreateForeignKeys: true);

            migrationBuilder.DropPrimaryKey(
                name: "PK_Locations",
                table: "Locations");

            migrationBuilder.DropUniqueConstraint(
                name: "IX_Locations_ChallengeId",
                table: "Locations",
                recreateForeignKeys: true);

            migrationBuilder.DropColumn(
                name: "Id",
                table: "PlayerGuesses");

            migrationBuilder.DropColumn(
                name: "Id",
                table: "Locations");

            migrationBuilder.RenameColumn(
                name: "Order",
                table: "PlayerGuesses",
                newName: "RoundNumber");

            migrationBuilder.AddPrimaryKey(
                name: "PK_PlayerGuesses",
                table: "PlayerGuesses",
                columns: new[] { "ChallengeId", "PlayerId", "RoundNumber" });

            migrationBuilder.AddPrimaryKey(
                name: "PK_Locations",
                table: "Locations",
                columns: new[] { "ChallengeId", "RoundNumber" });
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropPrimaryKey(
                name: "PK_PlayerGuesses",
                table: "PlayerGuesses");

            migrationBuilder.DropPrimaryKey(
                name: "PK_Locations",
                table: "Locations");

            migrationBuilder.RenameColumn(
                name: "RoundNumber",
                table: "PlayerGuesses",
                newName: "Order");

            migrationBuilder.AddColumn<int>(
                name: "Id",
                table: "PlayerGuesses",
                type: "int",
                nullable: false,
                defaultValue: 0)
                .Annotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

            migrationBuilder.AddColumn<int>(
                name: "Id",
                table: "Locations",
                type: "int",
                nullable: false,
                defaultValue: 0)
                .Annotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

            migrationBuilder.AddPrimaryKey(
                name: "PK_PlayerGuesses",
                table: "PlayerGuesses",
                column: "Id");

            migrationBuilder.AddPrimaryKey(
                name: "PK_Locations",
                table: "Locations",
                column: "Id");

            migrationBuilder.CreateIndex(
                name: "IX_PlayerGuesses_ChallengeId_PlayerId_Order",
                table: "PlayerGuesses",
                columns: new[] { "ChallengeId", "PlayerId", "Order" },
                unique: true);

            migrationBuilder.CreateIndex(
                name: "IX_Locations_ChallengeId",
                table: "Locations",
                column: "ChallengeId");
        }
    }
}
