// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

namespace GeoNRage.Server.Migrations
{
    public partial class ChangeLinkToGeoGuessrId : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("UPDATE Challenges SET Link = SUBSTRING_INDEX(Link, '/', -1)");

            migrationBuilder.RenameColumn(
                name: "Link",
                table: "Challenges",
                newName: "GeoGuessrId");

            migrationBuilder.RenameIndex(
                name: "IX_Challenges_Link",
                table: "Challenges",
                newName: "IX_Challenges_GeoGuessrId");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.RenameColumn(
                name: "GeoGuessrId",
                table: "Challenges",
                newName: "Link");

            migrationBuilder.RenameIndex(
                name: "IX_Challenges_GeoGuessrId",
                table: "Challenges",
                newName: "IX_Challenges_Link");
        }
    }
}
