// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

namespace GeoNRage.Server.Migrations
{
    public partial class UpdateDefaultGameId : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"SET FOREIGN_KEY_CHECKS=0;
UPDATE Games SET Id = -1 WHERE Id = 2147483647;
UPDATE Challenges SET GameId = -1 WHERE GameId = 2147483647;
SET FOREIGN_KEY_CHECKS=1;
ALTER TABLE Games AUTO_INCREMENT = 1;");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {

        }
    }
}
