// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace GeoNRage.Server.Migrations
{
    public partial class AddAssociatedPlayer : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<string>(
                name: "AssociatedPlayerId",
                table: "Players",
                type: "varchar(255)",
                nullable: true,
                collation: "utf8mb4_general_ci")
                .Annotation("MySql:CharSet", "utf8mb4");

            migrationBuilder.CreateIndex(
                name: "IX_Players_AssociatedPlayerId",
                table: "Players",
                column: "AssociatedPlayerId",
                unique: true);

            migrationBuilder.AddForeignKey(
                name: "FK_Players_Players_AssociatedPlayerId",
                table: "Players",
                column: "AssociatedPlayerId",
                principalTable: "Players",
                principalColumn: "Id");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_Players_Players_AssociatedPlayerId",
                table: "Players");

            migrationBuilder.DropIndex(
                name: "IX_Players_AssociatedPlayerId",
                table: "Players");

            migrationBuilder.DropColumn(
                name: "AssociatedPlayerId",
                table: "Players");
        }
    }
}
