// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace GeoNRage.Server.Migrations
{
    /// <inheritdoc />
    public partial class AddComputedSumToChallengeAndPlayerScore : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<int>(
                name: "Sum",
                table: "PlayerScores",
                type: "int",
                nullable: false,
                defaultValue: 0);

            migrationBuilder.AddColumn<int>(
                name: "MaxScore",
                table: "Challenges",
                type: "int",
                nullable: false,
                defaultValue: 0);

            migrationBuilder.Sql("""
                UPDATE PlayerScores ps
                JOIN (
                    SELECT ChallengeId, PlayerId, COALESCE(SUM(Score), 0) AS TotalScore
                    FROM PlayerGuesses
                    GROUP BY ChallengeId, PlayerId
                ) g ON ps.ChallengeId = g.ChallengeId AND ps.PlayerId = g.PlayerId
                SET ps.Sum = g.TotalScore;
                """);

            migrationBuilder.Sql("""
                UPDATE Challenges c
                JOIN (
                    SELECT ChallengeId, MAX(Sum) AS MaxPlayerScore
                    FROM PlayerScores
                    GROUP BY ChallengeId
                ) ps ON c.Id = ps.ChallengeId
                SET c.MaxScore = ps.MaxPlayerScore;
                """);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "Sum",
                table: "PlayerScores");

            migrationBuilder.DropColumn(
                name: "MaxScore",
                table: "Challenges");
        }
    }
}
