// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace GeoNRage.Server.Migrations
{
    /// <inheritdoc />
    public partial class FixSequences : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
                SELECT setval(
                    '"Games_Id_seq"',
                    10000
                );

                SELECT setval(
                    '"Challenges_Id_seq"',
                    10000
                );

                SELECT setval(
                    '"AspNetRoleClaims_Id_seq"',
                    10000
                );

                SELECT setval(
                    '"AspNetUserClaims_Id_seq"',
                    10000
                );
                
                SELECT setval(
                    '"DataProtectionKeys_Id_seq"',
                    10000
                );
                """);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {

        }
    }
}
