name: Build App

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v1
        with:
          fetch-depth: 0 # for minver
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
        shell: bash
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
      - name: Setup .NET Core for tools
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.300
      - name: Execute build
        run: |
          dotnet tool restore
          dotnet build --configuration Release /nologo
