name: Build App

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # for minver
      - name: Get the version
        id: get_version
        run: echo "VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_OUTPUT
        shell: bash
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
      - name: Execute build
        run: |
          dotnet build --configuration Release /nologo
